/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTemplatesIndexRouteImport } from './routes/_app/templates/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSegmentsIndexRouteImport } from './routes/_app/segments/index'
import { Route as AppOnboardingIndexRouteImport } from './routes/_app/onboarding/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppDeliveriesIndexRouteImport } from './routes/_app/deliveries/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppContactsIndexRouteImport } from './routes/_app/contacts/index'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app/campaigns/index'
import { Route as AppBroadcastsIndexRouteImport } from './routes/_app/broadcasts/index'
import { Route as AppAssetsIndexRouteImport } from './routes/_app/assets/index'
import { Route as AppSettingsTeamRouteImport } from './routes/_app/settings/team'
import { Route as AppSettingsGeneralRouteImport } from './routes/_app/settings/general'
import { Route as AppSettingsEmailRouteImport } from './routes/_app/settings/email'
import { Route as AppSettingsDomainRouteImport } from './routes/_app/settings/domain'
import { Route as AppSettingsApiKeysRouteImport } from './routes/_app/settings/api-keys'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSegmentsIndexRoute = AppSegmentsIndexRouteImport.update({
  id: '/segments/',
  path: '/segments/',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingIndexRoute = AppOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveriesIndexRoute = AppDeliveriesIndexRouteImport.update({
  id: '/deliveries/',
  path: '/deliveries/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const AppBroadcastsIndexRoute = AppBroadcastsIndexRouteImport.update({
  id: '/broadcasts/',
  path: '/broadcasts/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsGeneralRoute = AppSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsEmailRoute = AppSettingsEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDomainRoute = AppSettingsDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/domain': typeof AppSettingsDomainRoute
  '/settings/email': typeof AppSettingsEmailRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/assets/': typeof AppAssetsIndexRoute
  '/broadcasts/': typeof AppBroadcastsIndexRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/deliveries/': typeof AppDeliveriesIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/onboarding/': typeof AppOnboardingIndexRoute
  '/segments/': typeof AppSegmentsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/templates/': typeof AppTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/domain': typeof AppSettingsDomainRoute
  '/settings/email': typeof AppSettingsEmailRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/assets': typeof AppAssetsIndexRoute
  '/broadcasts': typeof AppBroadcastsIndexRoute
  '/campaigns': typeof AppCampaignsIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/deliveries': typeof AppDeliveriesIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/onboarding': typeof AppOnboardingIndexRoute
  '/segments': typeof AppSegmentsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/templates': typeof AppTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/_app/settings/domain': typeof AppSettingsDomainRoute
  '/_app/settings/email': typeof AppSettingsEmailRoute
  '/_app/settings/general': typeof AppSettingsGeneralRoute
  '/_app/settings/team': typeof AppSettingsTeamRoute
  '/_app/assets/': typeof AppAssetsIndexRoute
  '/_app/broadcasts/': typeof AppBroadcastsIndexRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/deliveries/': typeof AppDeliveriesIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/onboarding/': typeof AppOnboardingIndexRoute
  '/_app/segments/': typeof AppSegmentsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/templates/': typeof AppTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/invite/$token'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/domain'
    | '/settings/email'
    | '/settings/general'
    | '/settings/team'
    | '/assets/'
    | '/broadcasts/'
    | '/campaigns/'
    | '/contacts/'
    | '/dashboard/'
    | '/deliveries/'
    | '/events/'
    | '/onboarding/'
    | '/segments/'
    | '/settings/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/invite/$token'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/domain'
    | '/settings/email'
    | '/settings/general'
    | '/settings/team'
    | '/assets'
    | '/broadcasts'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/deliveries'
    | '/events'
    | '/onboarding'
    | '/segments'
    | '/settings'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/settings'
    | '/invite/$token'
    | '/_app/settings/account'
    | '/_app/settings/api-keys'
    | '/_app/settings/domain'
    | '/_app/settings/email'
    | '/_app/settings/general'
    | '/_app/settings/team'
    | '/_app/assets/'
    | '/_app/broadcasts/'
    | '/_app/campaigns/'
    | '/_app/contacts/'
    | '/_app/dashboard/'
    | '/_app/deliveries/'
    | '/_app/events/'
    | '/_app/onboarding/'
    | '/_app/segments/'
    | '/_app/settings/'
    | '/_app/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/': {
      id: '/_app/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/segments/': {
      id: '/_app/segments/'
      path: '/segments'
      fullPath: '/segments/'
      preLoaderRoute: typeof AppSegmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding/': {
      id: '/_app/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AppOnboardingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deliveries/': {
      id: '/_app/deliveries/'
      path: '/deliveries'
      fullPath: '/deliveries/'
      preLoaderRoute: typeof AppDeliveriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/broadcasts/': {
      id: '/_app/broadcasts/'
      path: '/broadcasts'
      fullPath: '/broadcasts/'
      preLoaderRoute: typeof AppBroadcastsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/': {
      id: '/_app/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/team': {
      id: '/_app/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/general': {
      id: '/_app/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AppSettingsGeneralRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/email': {
      id: '/_app/settings/email'
      path: '/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof AppSettingsEmailRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/domain': {
      id: '/_app/settings/domain'
      path: '/domain'
      fullPath: '/settings/domain'
      preLoaderRoute: typeof AppSettingsDomainRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/api-keys': {
      id: '/_app/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
  AppSettingsDomainRoute: typeof AppSettingsDomainRoute
  AppSettingsEmailRoute: typeof AppSettingsEmailRoute
  AppSettingsGeneralRoute: typeof AppSettingsGeneralRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
  AppSettingsDomainRoute: AppSettingsDomainRoute,
  AppSettingsEmailRoute: AppSettingsEmailRoute,
  AppSettingsGeneralRoute: AppSettingsGeneralRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
  AppBroadcastsIndexRoute: typeof AppBroadcastsIndexRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDeliveriesIndexRoute: typeof AppDeliveriesIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppOnboardingIndexRoute: typeof AppOnboardingIndexRoute
  AppSegmentsIndexRoute: typeof AppSegmentsIndexRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
  AppBroadcastsIndexRoute: AppBroadcastsIndexRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDeliveriesIndexRoute: AppDeliveriesIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppOnboardingIndexRoute: AppOnboardingIndexRoute,
  AppSegmentsIndexRoute: AppSegmentsIndexRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
